LitebondCoinPayment/src_20180916/Web/Controllers/ComissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Domain.Entities;
using Core.Domain.Models;
using Core.Services;
using Microsoft.AspNet.Identity.Owin;
using WebUI.Helpers;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize]
    public class ComissionController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly INetworkComissionService _networkComissionService;
        private readonly IHistoryNetworkIncomeService _historyNetworkIncomeService;
        private readonly IHistoryReceiveIncomeService _historyReceiveIncomeService;
        private readonly IIncomeService _incomeService;
        private readonly IProfitService _profitService;
        private readonly IProfitDailyService _profitDailyService;
        private readonly IProfitComissionService _profitComissionService;
        private readonly IHistoryDepositService _historyDepositService;
        private readonly ICoditionService _coditionService;
        private readonly IHistoryGetIncomeBalanceService _historyGetIncomeBalanceService;
        private readonly IHistoryGetProfitBalanceService _historyGetProfitBalanceService;
        private readonly IBalanceService _balanceService;
        private readonly AccountServiceExtension _accountServiceExtension;

        public ComissionController(
                            IAccountService accountService,
                            INetworkComissionService networkcomissionService,
                            IHistoryNetworkIncomeService historyNetworkIncomeService,
                             IHistoryReceiveIncomeService historyReceiveIncomeService,
                             IIncomeService incomeService,
                             IProfitService profitService,
                             IProfitComissionService profitComissionService,
                             IProfitDailyService profitDailyService,
                             IHistoryDepositService historyDepositService,
                             ICoditionService coditionService,
                             IHistoryGetIncomeBalanceService historyGetIncomeBalanceService,
                             IHistoryGetProfitBalanceService historyGetProfitBalanceService,
                             IBalanceService balanceService)
        {
            _accountService = accountService;
            _networkComissionService = networkcomissionService;
            _historyNetworkIncomeService = historyNetworkIncomeService;
            _historyReceiveIncomeService = historyReceiveIncomeService;
            _incomeService = incomeService;
            _profitService = profitService;
            _profitComissionService = profitComissionService;
            _profitDailyService = profitDailyService;
            _historyDepositService = historyDepositService;
            _coditionService = coditionService;
            _historyGetIncomeBalanceService = historyGetIncomeBalanceService;
            _historyGetProfitBalanceService = historyGetProfitBalanceService;
            _balanceService = balanceService;

            this._accountService = accountService;
            _accountServiceExtension = new AccountServiceExtension();
        }


        /// GET: Comission
        public ActionResult Index()
        {

            //Get Information of NetworkIncome
            var result = _profitComissionService.GetProfitIncomeByEmail(User.Identity.Name);
            return View(result);
        }


        /// <summary>
        /// NetworkIncome
        /// </summary>
        /// <returns></returns>
        public ActionResult NetworkIncome()
        {
            //Get Information of NetworkIncome
            var result = _networkComissionService.GetNetworkIncomeByEmail(User.Identity.Name);
            return View(result);
        }

        [HttpPost]
        public JsonResult updateStatusNetworkIncomeAndGetIncome(Int32 recordId, bool status, string amount)
        {
            var amountDecimal = decimal.Parse(amount.Replace(".", ",").ToString());
            var recordHistory = _historyNetworkIncomeService.GetHistoryNetworkById(recordId);
            if (recordHistory != null)
            {
                var result = _networkComissionService.UpdateStatusAndUpdateTotalAmountIncome(recordId, status, amountDecimal, User.Identity.Name);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json(null);
        }

        [HttpPost]
        public JsonResult updateStatusReferralAndGetIncome(Int32 recordId, bool status, string amount)
        {
            var amountDecimal = decimal.Parse(amount.Replace(".", ",").ToString());
            var recordHistory = _historyReceiveIncomeService.GetHistoryReceiveIncomeReferralById(recordId);
            if (recordHistory != null)
            {
                var result = _networkComissionService.UpdateStatusReferralIncomeAndUpdateTotalAmountIncome(recordId, status, amountDecimal, User.Identity.Name);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json(null);
        }

        [HttpPost]
        public JsonResult updateStatusReceiveProfit(Int32 recordId, bool status, string amount)
        {
            var amountProfitDaily = decimal.Parse(amount.Replace(".", ",").ToString());
            var recordHistory = _profitDailyService.GetProfitDailyById(recordId);
            if (recordHistory != null)
            {
                var result = _networkComissionService.UpdateStatusReceiveProfit(recordId, status, amountProfitDaily, User.Identity.Name);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json(null);
        }

        [HttpPost]
        public JsonResult insertDepositToData(string amount)
        {
            //Check Level For User and Check Level for Upline
            //Pay Network Commision
            //Pay 10% for Upline
            //Insert Deposit
            if (!string.IsNullOrEmpty(amount) && !(amount == "NaN"))
            {
                var amountP = decimal.Parse(amount.Replace(".", ",").ToString());
                var amountInBalance = _balanceService.GetByEmail(User.Identity.Name).TotalBalance;
                //Check Ltc in balance
                if (amountInBalance >= amountP)
                {
                    var totalDeposit = calTotalDeposit(User.Identity.Name);
                    switch (_accountService.GetByEmail(User.Identity.Name).Level)
                    {
                        case 0:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                                totalDeposit, _coditionService.Codition_Level_L().MinDeposit, _coditionService.Codition_Level_L().MaxDeposit);
                        case 1:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                                totalDeposit, _coditionService.Codition_Level_L1().MinDeposit, _coditionService.Codition_Level_L1().MaxDeposit);
                        case 2:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L2().MinDeposit, _coditionService.Codition_Level_L2().MaxDeposit);
                        case 3:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L3().MinDeposit, _coditionService.Codition_Level_L3().MaxDeposit);
                        case 4:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L4().MinDeposit, _coditionService.Codition_Level_L4().MaxDeposit);
                        case 5:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L5().MinDeposit, _coditionService.Codition_Level_L5().MaxDeposit);
                        case 6:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L6().MinDeposit, _coditionService.Codition_Level_L6().MaxDeposit);
                        case 7:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L7().MinDeposit, _coditionService.Codition_Level_L7().MaxDeposit);
                        case 8:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L8().MinDeposit, _coditionService.Codition_Level_L8().MaxDeposit);
                        case 9:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L9().MinDeposit, _coditionService.Codition_Level_L9().MaxDeposit);
                        case 10:
                            return returnJson(_accountService.GetByEmail(User.Identity.Name).Level, amountP,
                               totalDeposit, _coditionService.Codition_Level_L10().MinDeposit, _coditionService.Codition_Level_L10().MaxDeposit);
                    }
                }
                return Json(new { IsError = false, message = "Fail ! Your balance is not enough ! Please check your balance." });
            }

LitebondCoinPayment/src_20180916/Web/Views/Dashboard/Index.cshtml
@model Core.Domain.Models.DashboardModel
@{
    ViewBag.Title = "Dashboard";
}


<!-- new template -->

<div class="row">
    <div class="col-md-6">
        <div class="tile-item tile-primary">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">LITECOIN BALANCE</h6>
            <h1 class="tile-info">@Model.Balance LTC</h1>
        </div>
    </div><!-- .col -->
    <div class="col-md-6">
        <div class="tile-item tile-light">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">YOUR TOTAL ESCROW</h6>
            <ul class="tile-info-list">
                <li><span>@Model.Deposit LTC</span></li>
            </ul>
        </div>
    </div><!-- .col -->
    <div class="col-md-6">
        <div class="tile-item tile-light">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">YOUR TOTAL REFERRAL</h6>
            <ul class="tile-info-list">
                <li><span>@Model.TotalReferral REF</span></li>
            </ul>
        </div>
    </div><!-- .col -->
    <div class="col-md-6">
        <div class="tile-item tile-light">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">YOUR LEVEL</h6>
            <ul class="tile-info-list">
                <li><span>L @Model.Level</span></li>
            </ul>
        </div>
    </div><!-- .col -->
</div>

<div class="info-card info-card-bordered">
    <div class="row align-items-center">
        <div class="col-sm-3">
            <div class="info-card-image">
                <img src="~/Content/userpanel/images/vector-a.png" alt="vector">
            </div>
            <div class="gaps-2x d-md-none"></div>
        </div>
        <div class="col-sm-9">
            <h4>Thank you for your interest towards to our Crypto Projects : LITEBOND</h4>
            <p>You can escrow LTC in <a href="@Url.Action("Index", "Comission")">Escrowing</a> section.</p>
            <p>You can get quick notice of the project in our Telegram: <a href="htts://t.me/litebond">htts://t.me/litebond</a></p>
            <p>Don’t hesitate to invite your friends! If your invited referral escrowed litecoin then you get 10% bonus.</p>
        </div>
    </div>
</div>

<h6>Your referral link</h6>
<div class="refferal-info">
    <span class="refferal-copy-feedback copy-feedback"></span>
    <em class="fas fa-link"></em>
    <input type="text" class="refferal-address copy-address" value="@Model.ReferralLink" disabled>
    <a href="#" class="refferal-copy copy-trigger"><em class="ti ti-files"></em></a>
</div><!-- .refferal-info -->
<br />
<div class="row">
    <div class="col-md-12">
        <div class="tile-item tile-light">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">SERVER TIME</h6>
            <ul class="tile-info-list">
                <li><span>@DateTime.UtcNow.ToString("U", System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))</span></li>
            </ul>
        </div>
    </div>
    <div class="col-md-12">
        <div class="tile-item tile-light">
            <div class="tile-bubbles"></div>
            <h6 class="tile-title">CURRENT LITECOIN PRICE</h6>
            <ul class="tile-info-list">
                <li><span>1 LTC</span>LTC</li>
                <li><span>=</span>~</li>
                <li><span id="ltcPrice2"></span>USD</li>

            </ul>
        </div>
    </div>
</div>



@section Scripts{
    <script type="text/javascript">
        function doCopy() {
            /* Get the text field */
            var copyText = document.getElementById("referrallink");

            /* Select the text field */
            copyText.select();

            /* Copy the text inside the text field */
            document.execCommand("copy");

            /* Alert the copied text */
            swal({
                title: 'Copied',
                type: 'success',
                confirmButtonText: 'Ok'
            });
        }

        //getLtcPriceUSD2();
        //function getLtcPriceUSD2() {
        //    $.get('https://chain.so/api/v2/get_price/LTC/USD', function (response) {
        //        const priceLtc = response.data.prices[0].price;
        //        $('#ltcPrice2').text('$' + priceLtc);
        //    });
        //}

    </script>
}